from app.schemas.city import CityResponse


_CITY_CATALOG: list[CityResponse] = [
    CityResponse(
        slug="agra",
        name="Agra",
        headline="Interior Designers in Agra",
        description="Turn your dream home into reality with the best interior designers in Agra.",
        experience_center="Livspace Experience Center, Agra",
        address="1st floor, Sanjay Palace, Civil Lines, Agra, Uttar Pradesh 282002",
        timings="Monday to Saturday | 10 AM - 8 PM",
        phone="+91 9557930504, +91 9997700405",
        appointment_types=["Experience Centre Tour - 30 minutes", "Design consultation - 60 minutes"],
    ),
    CityResponse(
        slug="mumbai",
        name="Mumbai",
        headline="Interior Designers in Mumbai",
        description="Create a home that feels premium, practical, and personal in Mumbai.",
        experience_center="Livspace Experience Center, Mumbai",
        address="Andheri East, Mumbai, Maharashtra 400069",
        timings="Monday to Saturday | 10 AM - 8 PM",
        phone="+91 9557930504, +91 9997700405",
        appointment_types=["Experience Centre Tour - 30 minutes", "Design consultation - 60 minutes"],
    ),
    CityResponse(
        slug="hyderabad",
        name="Hyderabad",
        headline="Interior Designers in Hyderabad",
        description="Plan a functional home with a refined design language in Hyderabad.",
        experience_center="Livspace Experience Center, Hyderabad",
        address="HITEC City, Hyderabad, Telangana 500081",
        timings="Monday to Saturday | 10 AM - 8 PM",
        phone="+91 9557930504, +91 9997700405",
        appointment_types=["Experience Centre Tour - 30 minutes", "Design consultation - 60 minutes"],
    ),
    CityResponse(
        slug="noida",
        name="Noida",
        headline="Interior Designers in Noida",
        description="Transform your home with contemporary interior design solutions in Noida.",
        experience_center="NextGen Experience Center, Noida",
        address="Sector 18, Noida, Uttar Pradesh 201301",
        timings="Monday to Saturday | 10 AM - 8 PM",
        phone="+91 9557930504, +91 9997700405",
        appointment_types=["Experience Centre Tour - 30 minutes", "Design consultation - 60 minutes"],
    ),
    CityResponse(
        slug="greater-noida",
        name="Greater Noida",
        headline="Interior Designers in Greater Noida",
        description="Get practical and elegant interiors tailored for modern homes in Greater Noida.",
        experience_center="NextGen Experience Center, Greater Noida",
        address="Alpha 1, Greater Noida, Uttar Pradesh 201310",
        timings="Monday to Saturday | 10 AM - 8 PM",
        phone="+91 9557930504, +91 9997700405",
        appointment_types=["Experience Centre Tour - 30 minutes", "Design consultation - 60 minutes"],
    ),
    CityResponse(
        slug="jewar",
        name="Jewar",
        headline="Interior Designers in Jewar",
        description="Plan functional interiors and future-ready layouts for your home in Jewar.",
        experience_center="NextGen Service Center, Jewar",
        address="Jewar Town, Gautam Buddha Nagar, Uttar Pradesh",
        timings="Monday to Saturday | 10 AM - 8 PM",
        phone="+91 9557930504, +91 9997700405",
        appointment_types=["Virtual Consultation - 30 minutes", "Design consultation - 60 minutes"],
    ),
    CityResponse(
        slug="jaipur",
        name="Jaipur",
        headline="Interior Designers in Jaipur",
        description="Bring thoughtful design and premium finishes to your home in Jaipur.",
        experience_center="NextGen Experience Center, Jaipur",
        address="Vaishali Nagar, Jaipur, Rajasthan 302021",
        timings="Monday to Saturday | 10 AM - 8 PM",
        phone="+91 9557930504, +91 9997700405",
        appointment_types=["Experience Centre Tour - 30 minutes", "Design consultation - 60 minutes"],
    ),
    CityResponse(
        slug="mathura",
        name="Mathura",
        headline="Interior Designers in Mathura",
        description="Craft warm and efficient living spaces in Mathura with expert interior planning.",
        experience_center="NextGen Service Center, Mathura",
        address="Civil Lines, Mathura, Uttar Pradesh 281001",
        timings="Monday to Saturday | 10 AM - 8 PM",
        phone="+91 9557930504, +91 9997700405",
        appointment_types=["Virtual Consultation - 30 minutes", "Design consultation - 60 minutes"],
    ),
    CityResponse(
        slug="goa",
        name="Goa",
        headline="Interior Designers in Goa",
        description="Design breezy, elegant interiors that match your lifestyle in Goa.",
        experience_center="NextGen Experience Center, Goa",
        address="Panjim, Goa 403001",
        timings="Monday to Saturday | 10 AM - 8 PM",
        phone="+91 9557930504, +91 9997700405",
        appointment_types=["Experience Centre Tour - 30 minutes", "Design consultation - 60 minutes"],
    ),
    CityResponse(
        slug="moradabad",
        name="Moradabad",
        headline="Interior Designers in Moradabad",
        description="Get custom interior solutions for compact and large homes in Moradabad.",
        experience_center="NextGen Service Center, Moradabad",
        address="Civil Lines, Moradabad, Uttar Pradesh 244001",
        timings="Monday to Saturday | 10 AM - 8 PM",
        phone="+91 9557930504, +91 9997700405",
        appointment_types=["Virtual Consultation - 30 minutes", "Design consultation - 60 minutes"],
    ),
    CityResponse(
        slug="chandigarh",
        name="Chandigarh",
        headline="Interior Designers in Chandigarh",
        description="Build a polished and practical home with design experts in Chandigarh.",
        experience_center="NextGen Experience Center, Chandigarh",
        address="Sector 17, Chandigarh 160017",
        timings="Monday to Saturday | 10 AM - 8 PM",
        phone="+91 9557930504, +91 9997700405",
        appointment_types=["Experience Centre Tour - 30 minutes", "Design consultation - 60 minutes"],
    ),
    CityResponse(
        slug="dehradun",
        name="Dehradun",
        headline="Interior Designers in Dehradun",
        description="Create balanced and cozy interiors for your family home in Dehradun.",
        experience_center="NextGen Service Center, Dehradun",
        address="Rajpur Road, Dehradun, Uttarakhand 248001",
        timings="Monday to Saturday | 10 AM - 8 PM",
        phone="+91 9557930504, +91 9997700405",
        appointment_types=["Virtual Consultation - 30 minutes", "Design consultation - 60 minutes"],
    ),
    CityResponse(
        slug="rampur",
        name="Rampur",
        headline="Interior Designers in Rampur",
        description="Upgrade your home style in Rampur with end-to-end interior design support.",
        experience_center="NextGen Service Center, Rampur",
        address="Rampur, Uttar Pradesh 244901",
        timings="Monday to Saturday | 10 AM - 8 PM",
        phone="+91 9557930504, +91 9997700405",
        appointment_types=["Virtual Consultation - 30 minutes", "Design consultation - 60 minutes"],
    ),
    CityResponse(
        slug="bariley",
        name="Bariley",
        headline="Interior Designers in Bariley",
        description="Explore personalized interior concepts and execution support in Bariley.",
        experience_center="NextGen Service Center, Bariley",
        address="Bariley, Uttar Pradesh",
        timings="Monday to Saturday | 10 AM - 8 PM",
        phone="+91 9557930504, +91 9997700405",
        appointment_types=["Virtual Consultation - 30 minutes", "Design consultation - 60 minutes"],
    ),
    CityResponse(
        slug="aligarh",
        name="Aligarh",
        headline="Interior Designers in Aligarh",
        description="Design your interiors with smart storage and modern finishes in Aligarh.",
        experience_center="NextGen Service Center, Aligarh",
        address="Civil Lines, Aligarh, Uttar Pradesh 202001",
        timings="Monday to Saturday | 10 AM - 8 PM",
        phone="+91 9557930504, +91 9997700405",
        appointment_types=["Virtual Consultation - 30 minutes", "Design consultation - 60 minutes"],
    ),
    CityResponse(
        slug="vrindavan",
        name="Vrindavan",
        headline="Interior Designers in Vrindavan",
        description="Create peaceful and elegant living spaces with expert designers in Vrindavan.",
        experience_center="NextGen Service Center, Vrindavan",
        address="Vrindavan, Uttar Pradesh 281121",
        timings="Monday to Saturday | 10 AM - 8 PM",
        phone="+91 9557930504, +91 9997700405",
        appointment_types=["Virtual Consultation - 30 minutes", "Design consultation - 60 minutes"],
    ),
]


def get_city_catalog() -> list[CityResponse]:
    return _CITY_CATALOG


def get_city_by_slug(city_slug: str) -> CityResponse | None:
    normalized_slug = city_slug.strip().lower()
    for city in _CITY_CATALOG:
        if city.slug == normalized_slug:
            return city
    return None
