/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoreLocatorRouteImport } from './routes/store-locator'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PriceCalculatorRouteImport } from './routes/price-calculator'
import { Route as MagazineRouteImport } from './routes/magazine'
import { Route as LuxuryInteriorsRouteImport } from './routes/luxury-interiors'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HireADesignerRouteImport } from './routes/hire-a-designer'
import { Route as DesignIdeasRouteImport } from './routes/design-ideas'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CitiesRouteImport } from './routes/cities'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MagazineIndexRouteImport } from './routes/magazine/index'
import { Route as DesignIdeasIndexRouteImport } from './routes/design-ideas/index'
import { Route as CitiesIndexRouteImport } from './routes/cities/index'
import { Route as MagazineWallDesignIdeasRouteImport } from './routes/magazine/wall-design-ideas'
import { Route as MagazineVastuTipsRouteImport } from './routes/magazine/vastu-tips'
import { Route as MagazineRoomIdeasRouteImport } from './routes/magazine/room-ideas'
import { Route as MagazineMaterialsGuideRouteImport } from './routes/magazine/materials-guide'
import { Route as MagazineLightingIdeasRouteImport } from './routes/magazine/lighting-ideas'
import { Route as MagazineInteriorAdviceRouteImport } from './routes/magazine/interior-advice'
import { Route as MagazineHomeRenovationIdeasRouteImport } from './routes/magazine/home-renovation-ideas'
import { Route as MagazineHomeOrganisationRouteImport } from './routes/magazine/home-organisation'
import { Route as MagazineHomeDecorRouteImport } from './routes/magazine/home-decor'
import { Route as MagazineFurnitureIdeasRouteImport } from './routes/magazine/furniture-ideas'
import { Route as MagazineExpertAdviceRouteImport } from './routes/magazine/expert-advice'
import { Route as MagazineDecorAndInspirationRouteImport } from './routes/magazine/decor-and-inspiration'
import { Route as MagazineCommercialInteriorsRouteImport } from './routes/magazine/commercial-interiors'
import { Route as MagazineCeilingDesignRouteImport } from './routes/magazine/ceiling-design'
import { Route as MagazineSlugRouteImport } from './routes/magazine/$slug'
import { Route as DesignIdeasWindowDesignsRouteImport } from './routes/design-ideas/window-designs'
import { Route as DesignIdeasWardrobeDesignsRouteImport } from './routes/design-ideas/wardrobe-designs'
import { Route as DesignIdeasWallPaintDesignsRouteImport } from './routes/design-ideas/wall-paint-designs'
import { Route as DesignIdeasWallDecorDesignsRouteImport } from './routes/design-ideas/wall-decor-designs'
import { Route as DesignIdeasTvUnitDesignsRouteImport } from './routes/design-ideas/tv-unit-designs'
import { Route as DesignIdeasTileDesignsRouteImport } from './routes/design-ideas/tile-designs'
import { Route as DesignIdeasStudyRoomDesignsRouteImport } from './routes/design-ideas/study-room-designs'
import { Route as DesignIdeasStaircaseDesignsRouteImport } from './routes/design-ideas/staircase-designs'
import { Route as DesignIdeasSpaceSavingDesignsRouteImport } from './routes/design-ideas/space-saving-designs'
import { Route as DesignIdeasPoojaRoomDesignsRouteImport } from './routes/design-ideas/pooja-room-designs'
import { Route as DesignIdeasMasterBedroomDesignsRouteImport } from './routes/design-ideas/master-bedroom-designs'
import { Route as DesignIdeasLivingRoomDesignsRouteImport } from './routes/design-ideas/living-room-designs'
import { Route as DesignIdeasKitchenSinksRouteImport } from './routes/design-ideas/kitchen-sinks'
import { Route as DesignIdeasKitchenDesignsRouteImport } from './routes/design-ideas/kitchen-designs'
import { Route as DesignIdeasKidsBedroomDesignsRouteImport } from './routes/design-ideas/kids-bedroom-designs'
import { Route as DesignIdeasHomesByNextgenRouteImport } from './routes/design-ideas/homes-by-nextgen'
import { Route as DesignIdeasHomeWallpaperDesignsRouteImport } from './routes/design-ideas/home-wallpaper-designs'
import { Route as DesignIdeasHomeOfficeDesignsRouteImport } from './routes/design-ideas/home-office-designs'
import { Route as DesignIdeasHomeBarDesignsRouteImport } from './routes/design-ideas/home-bar-designs'
import { Route as DesignIdeasGuestBedroomDesignsRouteImport } from './routes/design-ideas/guest-bedroom-designs'
import { Route as DesignIdeasFoyerDesignsRouteImport } from './routes/design-ideas/foyer-designs'
import { Route as DesignIdeasFlooringDesignsRouteImport } from './routes/design-ideas/flooring-designs'
import { Route as DesignIdeasFalseCeilingDesignsRouteImport } from './routes/design-ideas/false-ceiling-designs'
import { Route as DesignIdeasDoorDesignsRouteImport } from './routes/design-ideas/door-designs'
import { Route as DesignIdeasDiningRoomDesignsRouteImport } from './routes/design-ideas/dining-room-designs'
import { Route as DesignIdeasCrockeryUnitsRouteImport } from './routes/design-ideas/crockery-units'
import { Route as DesignIdeasBathroomDesignsRouteImport } from './routes/design-ideas/bathroom-designs'
import { Route as DesignIdeasBalconyDesignsRouteImport } from './routes/design-ideas/balcony-designs'
import { Route as DesignIdeasSlugRouteImport } from './routes/design-ideas/$slug'
import { Route as CitiesCityRouteImport } from './routes/cities/$city'
import { Route as MagazineBlogSlugRouteImport } from './routes/magazine/blog/$slug'

const StoreLocatorRoute = StoreLocatorRouteImport.update({
  id: '/store-locator',
  path: '/store-locator',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PriceCalculatorRoute = PriceCalculatorRouteImport.update({
  id: '/price-calculator',
  path: '/price-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const MagazineRoute = MagazineRouteImport.update({
  id: '/magazine',
  path: '/magazine',
  getParentRoute: () => rootRouteImport,
} as any)
const LuxuryInteriorsRoute = LuxuryInteriorsRouteImport.update({
  id: '/luxury-interiors',
  path: '/luxury-interiors',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HireADesignerRoute = HireADesignerRouteImport.update({
  id: '/hire-a-designer',
  path: '/hire-a-designer',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignIdeasRoute = DesignIdeasRouteImport.update({
  id: '/design-ideas',
  path: '/design-ideas',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesRoute = CitiesRouteImport.update({
  id: '/cities',
  path: '/cities',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MagazineIndexRoute = MagazineIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MagazineRoute,
} as any)
const DesignIdeasIndexRoute = DesignIdeasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DesignIdeasRoute,
} as any)
const CitiesIndexRoute = CitiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CitiesRoute,
} as any)
const MagazineWallDesignIdeasRoute = MagazineWallDesignIdeasRouteImport.update({
  id: '/wall-design-ideas',
  path: '/wall-design-ideas',
  getParentRoute: () => MagazineRoute,
} as any)
const MagazineVastuTipsRoute = MagazineVastuTipsRouteImport.update({
  id: '/vastu-tips',
  path: '/vastu-tips',
  getParentRoute: () => MagazineRoute,
} as any)
const MagazineRoomIdeasRoute = MagazineRoomIdeasRouteImport.update({
  id: '/room-ideas',
  path: '/room-ideas',
  getParentRoute: () => MagazineRoute,
} as any)
const MagazineMaterialsGuideRoute = MagazineMaterialsGuideRouteImport.update({
  id: '/materials-guide',
  path: '/materials-guide',
  getParentRoute: () => MagazineRoute,
} as any)
const MagazineLightingIdeasRoute = MagazineLightingIdeasRouteImport.update({
  id: '/lighting-ideas',
  path: '/lighting-ideas',
  getParentRoute: () => MagazineRoute,
} as any)
const MagazineInteriorAdviceRoute = MagazineInteriorAdviceRouteImport.update({
  id: '/interior-advice',
  path: '/interior-advice',
  getParentRoute: () => MagazineRoute,
} as any)
const MagazineHomeRenovationIdeasRoute =
  MagazineHomeRenovationIdeasRouteImport.update({
    id: '/home-renovation-ideas',
    path: '/home-renovation-ideas',
    getParentRoute: () => MagazineRoute,
  } as any)
const MagazineHomeOrganisationRoute =
  MagazineHomeOrganisationRouteImport.update({
    id: '/home-organisation',
    path: '/home-organisation',
    getParentRoute: () => MagazineRoute,
  } as any)
const MagazineHomeDecorRoute = MagazineHomeDecorRouteImport.update({
  id: '/home-decor',
  path: '/home-decor',
  getParentRoute: () => MagazineRoute,
} as any)
const MagazineFurnitureIdeasRoute = MagazineFurnitureIdeasRouteImport.update({
  id: '/furniture-ideas',
  path: '/furniture-ideas',
  getParentRoute: () => MagazineRoute,
} as any)
const MagazineExpertAdviceRoute = MagazineExpertAdviceRouteImport.update({
  id: '/expert-advice',
  path: '/expert-advice',
  getParentRoute: () => MagazineRoute,
} as any)
const MagazineDecorAndInspirationRoute =
  MagazineDecorAndInspirationRouteImport.update({
    id: '/decor-and-inspiration',
    path: '/decor-and-inspiration',
    getParentRoute: () => MagazineRoute,
  } as any)
const MagazineCommercialInteriorsRoute =
  MagazineCommercialInteriorsRouteImport.update({
    id: '/commercial-interiors',
    path: '/commercial-interiors',
    getParentRoute: () => MagazineRoute,
  } as any)
const MagazineCeilingDesignRoute = MagazineCeilingDesignRouteImport.update({
  id: '/ceiling-design',
  path: '/ceiling-design',
  getParentRoute: () => MagazineRoute,
} as any)
const MagazineSlugRoute = MagazineSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MagazineRoute,
} as any)
const DesignIdeasWindowDesignsRoute =
  DesignIdeasWindowDesignsRouteImport.update({
    id: '/window-designs',
    path: '/window-designs',
    getParentRoute: () => DesignIdeasRoute,
  } as any)
const DesignIdeasWardrobeDesignsRoute =
  DesignIdeasWardrobeDesignsRouteImport.update({
    id: '/wardrobe-designs',
    path: '/wardrobe-designs',
    getParentRoute: () => DesignIdeasRoute,
  } as any)
const DesignIdeasWallPaintDesignsRoute =
  DesignIdeasWallPaintDesignsRouteImport.update({
    id: '/wall-paint-designs',
    path: '/wall-paint-designs',
    getParentRoute: () => DesignIdeasRoute,
  } as any)
const DesignIdeasWallDecorDesignsRoute =
  DesignIdeasWallDecorDesignsRouteImport.update({
    id: '/wall-decor-designs',
    path: '/wall-decor-designs',
    getParentRoute: () => DesignIdeasRoute,
  } as any)
const DesignIdeasTvUnitDesignsRoute =
  DesignIdeasTvUnitDesignsRouteImport.update({
    id: '/tv-unit-designs',
    path: '/tv-unit-designs',
    getParentRoute: () => DesignIdeasRoute,
  } as any)
const DesignIdeasTileDesignsRoute = DesignIdeasTileDesignsRouteImport.update({
  id: '/tile-designs',
  path: '/tile-designs',
  getParentRoute: () => DesignIdeasRoute,
} as any)
const DesignIdeasStudyRoomDesignsRoute =
  DesignIdeasStudyRoomDesignsRouteImport.update({
    id: '/study-room-designs',
    path: '/study-room-designs',
    getParentRoute: () => DesignIdeasRoute,
  } as any)
const DesignIdeasStaircaseDesignsRoute =
  DesignIdeasStaircaseDesignsRouteImport.update({
    id: '/staircase-designs',
    path: '/staircase-designs',
    getParentRoute: () => DesignIdeasRoute,
  } as any)
const DesignIdeasSpaceSavingDesignsRoute =
  DesignIdeasSpaceSavingDesignsRouteImport.update({
    id: '/space-saving-designs',
    path: '/space-saving-designs',
    getParentRoute: () => DesignIdeasRoute,
  } as any)
const DesignIdeasPoojaRoomDesignsRoute =
  DesignIdeasPoojaRoomDesignsRouteImport.update({
    id: '/pooja-room-designs',
    path: '/pooja-room-designs',
    getParentRoute: () => DesignIdeasRoute,
  } as any)
const DesignIdeasMasterBedroomDesignsRoute =
  DesignIdeasMasterBedroomDesignsRouteImport.update({
    id: '/master-bedroom-designs',
    path: '/master-bedroom-designs',
    getParentRoute: () => DesignIdeasRoute,
  } as any)
const DesignIdeasLivingRoomDesignsRoute =
  DesignIdeasLivingRoomDesignsRouteImport.update({
    id: '/living-room-designs',
    path: '/living-room-designs',
    getParentRoute: () => DesignIdeasRoute,
  } as any)
const DesignIdeasKitchenSinksRoute = DesignIdeasKitchenSinksRouteImport.update({
  id: '/kitchen-sinks',
  path: '/kitchen-sinks',
  getParentRoute: () => DesignIdeasRoute,
} as any)
const DesignIdeasKitchenDesignsRoute =
  DesignIdeasKitchenDesignsRouteImport.update({
    id: '/kitchen-designs',
    path: '/kitchen-designs',
    getParentRoute: () => DesignIdeasRoute,
  } as any)
const DesignIdeasKidsBedroomDesignsRoute =
  DesignIdeasKidsBedroomDesignsRouteImport.update({
    id: '/kids-bedroom-designs',
    path: '/kids-bedroom-designs',
    getParentRoute: () => DesignIdeasRoute,
  } as any)
const DesignIdeasHomesByNextgenRoute =
  DesignIdeasHomesByNextgenRouteImport.update({
    id: '/homes-by-nextgen',
    path: '/homes-by-nextgen',
    getParentRoute: () => DesignIdeasRoute,
  } as any)
const DesignIdeasHomeWallpaperDesignsRoute =
  DesignIdeasHomeWallpaperDesignsRouteImport.update({
    id: '/home-wallpaper-designs',
    path: '/home-wallpaper-designs',
    getParentRoute: () => DesignIdeasRoute,
  } as any)
const DesignIdeasHomeOfficeDesignsRoute =
  DesignIdeasHomeOfficeDesignsRouteImport.update({
    id: '/home-office-designs',
    path: '/home-office-designs',
    getParentRoute: () => DesignIdeasRoute,
  } as any)
const DesignIdeasHomeBarDesignsRoute =
  DesignIdeasHomeBarDesignsRouteImport.update({
    id: '/home-bar-designs',
    path: '/home-bar-designs',
    getParentRoute: () => DesignIdeasRoute,
  } as any)
const DesignIdeasGuestBedroomDesignsRoute =
  DesignIdeasGuestBedroomDesignsRouteImport.update({
    id: '/guest-bedroom-designs',
    path: '/guest-bedroom-designs',
    getParentRoute: () => DesignIdeasRoute,
  } as any)
const DesignIdeasFoyerDesignsRoute = DesignIdeasFoyerDesignsRouteImport.update({
  id: '/foyer-designs',
  path: '/foyer-designs',
  getParentRoute: () => DesignIdeasRoute,
} as any)
const DesignIdeasFlooringDesignsRoute =
  DesignIdeasFlooringDesignsRouteImport.update({
    id: '/flooring-designs',
    path: '/flooring-designs',
    getParentRoute: () => DesignIdeasRoute,
  } as any)
const DesignIdeasFalseCeilingDesignsRoute =
  DesignIdeasFalseCeilingDesignsRouteImport.update({
    id: '/false-ceiling-designs',
    path: '/false-ceiling-designs',
    getParentRoute: () => DesignIdeasRoute,
  } as any)
const DesignIdeasDoorDesignsRoute = DesignIdeasDoorDesignsRouteImport.update({
  id: '/door-designs',
  path: '/door-designs',
  getParentRoute: () => DesignIdeasRoute,
} as any)
const DesignIdeasDiningRoomDesignsRoute =
  DesignIdeasDiningRoomDesignsRouteImport.update({
    id: '/dining-room-designs',
    path: '/dining-room-designs',
    getParentRoute: () => DesignIdeasRoute,
  } as any)
const DesignIdeasCrockeryUnitsRoute =
  DesignIdeasCrockeryUnitsRouteImport.update({
    id: '/crockery-units',
    path: '/crockery-units',
    getParentRoute: () => DesignIdeasRoute,
  } as any)
const DesignIdeasBathroomDesignsRoute =
  DesignIdeasBathroomDesignsRouteImport.update({
    id: '/bathroom-designs',
    path: '/bathroom-designs',
    getParentRoute: () => DesignIdeasRoute,
  } as any)
const DesignIdeasBalconyDesignsRoute =
  DesignIdeasBalconyDesignsRouteImport.update({
    id: '/balcony-designs',
    path: '/balcony-designs',
    getParentRoute: () => DesignIdeasRoute,
  } as any)
const DesignIdeasSlugRoute = DesignIdeasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DesignIdeasRoute,
} as any)
const CitiesCityRoute = CitiesCityRouteImport.update({
  id: '/$city',
  path: '/$city',
  getParentRoute: () => CitiesRoute,
} as any)
const MagazineBlogSlugRoute = MagazineBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => MagazineRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/cities': typeof CitiesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/design-ideas': typeof DesignIdeasRouteWithChildren
  '/hire-a-designer': typeof HireADesignerRoute
  '/login': typeof LoginRoute
  '/luxury-interiors': typeof LuxuryInteriorsRoute
  '/magazine': typeof MagazineRouteWithChildren
  '/price-calculator': typeof PriceCalculatorRoute
  '/projects': typeof ProjectsRoute
  '/store-locator': typeof StoreLocatorRoute
  '/cities/$city': typeof CitiesCityRoute
  '/design-ideas/$slug': typeof DesignIdeasSlugRoute
  '/design-ideas/balcony-designs': typeof DesignIdeasBalconyDesignsRoute
  '/design-ideas/bathroom-designs': typeof DesignIdeasBathroomDesignsRoute
  '/design-ideas/crockery-units': typeof DesignIdeasCrockeryUnitsRoute
  '/design-ideas/dining-room-designs': typeof DesignIdeasDiningRoomDesignsRoute
  '/design-ideas/door-designs': typeof DesignIdeasDoorDesignsRoute
  '/design-ideas/false-ceiling-designs': typeof DesignIdeasFalseCeilingDesignsRoute
  '/design-ideas/flooring-designs': typeof DesignIdeasFlooringDesignsRoute
  '/design-ideas/foyer-designs': typeof DesignIdeasFoyerDesignsRoute
  '/design-ideas/guest-bedroom-designs': typeof DesignIdeasGuestBedroomDesignsRoute
  '/design-ideas/home-bar-designs': typeof DesignIdeasHomeBarDesignsRoute
  '/design-ideas/home-office-designs': typeof DesignIdeasHomeOfficeDesignsRoute
  '/design-ideas/home-wallpaper-designs': typeof DesignIdeasHomeWallpaperDesignsRoute
  '/design-ideas/homes-by-nextgen': typeof DesignIdeasHomesByNextgenRoute
  '/design-ideas/kids-bedroom-designs': typeof DesignIdeasKidsBedroomDesignsRoute
  '/design-ideas/kitchen-designs': typeof DesignIdeasKitchenDesignsRoute
  '/design-ideas/kitchen-sinks': typeof DesignIdeasKitchenSinksRoute
  '/design-ideas/living-room-designs': typeof DesignIdeasLivingRoomDesignsRoute
  '/design-ideas/master-bedroom-designs': typeof DesignIdeasMasterBedroomDesignsRoute
  '/design-ideas/pooja-room-designs': typeof DesignIdeasPoojaRoomDesignsRoute
  '/design-ideas/space-saving-designs': typeof DesignIdeasSpaceSavingDesignsRoute
  '/design-ideas/staircase-designs': typeof DesignIdeasStaircaseDesignsRoute
  '/design-ideas/study-room-designs': typeof DesignIdeasStudyRoomDesignsRoute
  '/design-ideas/tile-designs': typeof DesignIdeasTileDesignsRoute
  '/design-ideas/tv-unit-designs': typeof DesignIdeasTvUnitDesignsRoute
  '/design-ideas/wall-decor-designs': typeof DesignIdeasWallDecorDesignsRoute
  '/design-ideas/wall-paint-designs': typeof DesignIdeasWallPaintDesignsRoute
  '/design-ideas/wardrobe-designs': typeof DesignIdeasWardrobeDesignsRoute
  '/design-ideas/window-designs': typeof DesignIdeasWindowDesignsRoute
  '/magazine/$slug': typeof MagazineSlugRoute
  '/magazine/ceiling-design': typeof MagazineCeilingDesignRoute
  '/magazine/commercial-interiors': typeof MagazineCommercialInteriorsRoute
  '/magazine/decor-and-inspiration': typeof MagazineDecorAndInspirationRoute
  '/magazine/expert-advice': typeof MagazineExpertAdviceRoute
  '/magazine/furniture-ideas': typeof MagazineFurnitureIdeasRoute
  '/magazine/home-decor': typeof MagazineHomeDecorRoute
  '/magazine/home-organisation': typeof MagazineHomeOrganisationRoute
  '/magazine/home-renovation-ideas': typeof MagazineHomeRenovationIdeasRoute
  '/magazine/interior-advice': typeof MagazineInteriorAdviceRoute
  '/magazine/lighting-ideas': typeof MagazineLightingIdeasRoute
  '/magazine/materials-guide': typeof MagazineMaterialsGuideRoute
  '/magazine/room-ideas': typeof MagazineRoomIdeasRoute
  '/magazine/vastu-tips': typeof MagazineVastuTipsRoute
  '/magazine/wall-design-ideas': typeof MagazineWallDesignIdeasRoute
  '/cities/': typeof CitiesIndexRoute
  '/design-ideas/': typeof DesignIdeasIndexRoute
  '/magazine/': typeof MagazineIndexRoute
  '/magazine/blog/$slug': typeof MagazineBlogSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/hire-a-designer': typeof HireADesignerRoute
  '/login': typeof LoginRoute
  '/luxury-interiors': typeof LuxuryInteriorsRoute
  '/price-calculator': typeof PriceCalculatorRoute
  '/projects': typeof ProjectsRoute
  '/store-locator': typeof StoreLocatorRoute
  '/cities/$city': typeof CitiesCityRoute
  '/design-ideas/$slug': typeof DesignIdeasSlugRoute
  '/design-ideas/balcony-designs': typeof DesignIdeasBalconyDesignsRoute
  '/design-ideas/bathroom-designs': typeof DesignIdeasBathroomDesignsRoute
  '/design-ideas/crockery-units': typeof DesignIdeasCrockeryUnitsRoute
  '/design-ideas/dining-room-designs': typeof DesignIdeasDiningRoomDesignsRoute
  '/design-ideas/door-designs': typeof DesignIdeasDoorDesignsRoute
  '/design-ideas/false-ceiling-designs': typeof DesignIdeasFalseCeilingDesignsRoute
  '/design-ideas/flooring-designs': typeof DesignIdeasFlooringDesignsRoute
  '/design-ideas/foyer-designs': typeof DesignIdeasFoyerDesignsRoute
  '/design-ideas/guest-bedroom-designs': typeof DesignIdeasGuestBedroomDesignsRoute
  '/design-ideas/home-bar-designs': typeof DesignIdeasHomeBarDesignsRoute
  '/design-ideas/home-office-designs': typeof DesignIdeasHomeOfficeDesignsRoute
  '/design-ideas/home-wallpaper-designs': typeof DesignIdeasHomeWallpaperDesignsRoute
  '/design-ideas/homes-by-nextgen': typeof DesignIdeasHomesByNextgenRoute
  '/design-ideas/kids-bedroom-designs': typeof DesignIdeasKidsBedroomDesignsRoute
  '/design-ideas/kitchen-designs': typeof DesignIdeasKitchenDesignsRoute
  '/design-ideas/kitchen-sinks': typeof DesignIdeasKitchenSinksRoute
  '/design-ideas/living-room-designs': typeof DesignIdeasLivingRoomDesignsRoute
  '/design-ideas/master-bedroom-designs': typeof DesignIdeasMasterBedroomDesignsRoute
  '/design-ideas/pooja-room-designs': typeof DesignIdeasPoojaRoomDesignsRoute
  '/design-ideas/space-saving-designs': typeof DesignIdeasSpaceSavingDesignsRoute
  '/design-ideas/staircase-designs': typeof DesignIdeasStaircaseDesignsRoute
  '/design-ideas/study-room-designs': typeof DesignIdeasStudyRoomDesignsRoute
  '/design-ideas/tile-designs': typeof DesignIdeasTileDesignsRoute
  '/design-ideas/tv-unit-designs': typeof DesignIdeasTvUnitDesignsRoute
  '/design-ideas/wall-decor-designs': typeof DesignIdeasWallDecorDesignsRoute
  '/design-ideas/wall-paint-designs': typeof DesignIdeasWallPaintDesignsRoute
  '/design-ideas/wardrobe-designs': typeof DesignIdeasWardrobeDesignsRoute
  '/design-ideas/window-designs': typeof DesignIdeasWindowDesignsRoute
  '/magazine/$slug': typeof MagazineSlugRoute
  '/magazine/ceiling-design': typeof MagazineCeilingDesignRoute
  '/magazine/commercial-interiors': typeof MagazineCommercialInteriorsRoute
  '/magazine/decor-and-inspiration': typeof MagazineDecorAndInspirationRoute
  '/magazine/expert-advice': typeof MagazineExpertAdviceRoute
  '/magazine/furniture-ideas': typeof MagazineFurnitureIdeasRoute
  '/magazine/home-decor': typeof MagazineHomeDecorRoute
  '/magazine/home-organisation': typeof MagazineHomeOrganisationRoute
  '/magazine/home-renovation-ideas': typeof MagazineHomeRenovationIdeasRoute
  '/magazine/interior-advice': typeof MagazineInteriorAdviceRoute
  '/magazine/lighting-ideas': typeof MagazineLightingIdeasRoute
  '/magazine/materials-guide': typeof MagazineMaterialsGuideRoute
  '/magazine/room-ideas': typeof MagazineRoomIdeasRoute
  '/magazine/vastu-tips': typeof MagazineVastuTipsRoute
  '/magazine/wall-design-ideas': typeof MagazineWallDesignIdeasRoute
  '/cities': typeof CitiesIndexRoute
  '/design-ideas': typeof DesignIdeasIndexRoute
  '/magazine': typeof MagazineIndexRoute
  '/magazine/blog/$slug': typeof MagazineBlogSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/cities': typeof CitiesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/design-ideas': typeof DesignIdeasRouteWithChildren
  '/hire-a-designer': typeof HireADesignerRoute
  '/login': typeof LoginRoute
  '/luxury-interiors': typeof LuxuryInteriorsRoute
  '/magazine': typeof MagazineRouteWithChildren
  '/price-calculator': typeof PriceCalculatorRoute
  '/projects': typeof ProjectsRoute
  '/store-locator': typeof StoreLocatorRoute
  '/cities/$city': typeof CitiesCityRoute
  '/design-ideas/$slug': typeof DesignIdeasSlugRoute
  '/design-ideas/balcony-designs': typeof DesignIdeasBalconyDesignsRoute
  '/design-ideas/bathroom-designs': typeof DesignIdeasBathroomDesignsRoute
  '/design-ideas/crockery-units': typeof DesignIdeasCrockeryUnitsRoute
  '/design-ideas/dining-room-designs': typeof DesignIdeasDiningRoomDesignsRoute
  '/design-ideas/door-designs': typeof DesignIdeasDoorDesignsRoute
  '/design-ideas/false-ceiling-designs': typeof DesignIdeasFalseCeilingDesignsRoute
  '/design-ideas/flooring-designs': typeof DesignIdeasFlooringDesignsRoute
  '/design-ideas/foyer-designs': typeof DesignIdeasFoyerDesignsRoute
  '/design-ideas/guest-bedroom-designs': typeof DesignIdeasGuestBedroomDesignsRoute
  '/design-ideas/home-bar-designs': typeof DesignIdeasHomeBarDesignsRoute
  '/design-ideas/home-office-designs': typeof DesignIdeasHomeOfficeDesignsRoute
  '/design-ideas/home-wallpaper-designs': typeof DesignIdeasHomeWallpaperDesignsRoute
  '/design-ideas/homes-by-nextgen': typeof DesignIdeasHomesByNextgenRoute
  '/design-ideas/kids-bedroom-designs': typeof DesignIdeasKidsBedroomDesignsRoute
  '/design-ideas/kitchen-designs': typeof DesignIdeasKitchenDesignsRoute
  '/design-ideas/kitchen-sinks': typeof DesignIdeasKitchenSinksRoute
  '/design-ideas/living-room-designs': typeof DesignIdeasLivingRoomDesignsRoute
  '/design-ideas/master-bedroom-designs': typeof DesignIdeasMasterBedroomDesignsRoute
  '/design-ideas/pooja-room-designs': typeof DesignIdeasPoojaRoomDesignsRoute
  '/design-ideas/space-saving-designs': typeof DesignIdeasSpaceSavingDesignsRoute
  '/design-ideas/staircase-designs': typeof DesignIdeasStaircaseDesignsRoute
  '/design-ideas/study-room-designs': typeof DesignIdeasStudyRoomDesignsRoute
  '/design-ideas/tile-designs': typeof DesignIdeasTileDesignsRoute
  '/design-ideas/tv-unit-designs': typeof DesignIdeasTvUnitDesignsRoute
  '/design-ideas/wall-decor-designs': typeof DesignIdeasWallDecorDesignsRoute
  '/design-ideas/wall-paint-designs': typeof DesignIdeasWallPaintDesignsRoute
  '/design-ideas/wardrobe-designs': typeof DesignIdeasWardrobeDesignsRoute
  '/design-ideas/window-designs': typeof DesignIdeasWindowDesignsRoute
  '/magazine/$slug': typeof MagazineSlugRoute
  '/magazine/ceiling-design': typeof MagazineCeilingDesignRoute
  '/magazine/commercial-interiors': typeof MagazineCommercialInteriorsRoute
  '/magazine/decor-and-inspiration': typeof MagazineDecorAndInspirationRoute
  '/magazine/expert-advice': typeof MagazineExpertAdviceRoute
  '/magazine/furniture-ideas': typeof MagazineFurnitureIdeasRoute
  '/magazine/home-decor': typeof MagazineHomeDecorRoute
  '/magazine/home-organisation': typeof MagazineHomeOrganisationRoute
  '/magazine/home-renovation-ideas': typeof MagazineHomeRenovationIdeasRoute
  '/magazine/interior-advice': typeof MagazineInteriorAdviceRoute
  '/magazine/lighting-ideas': typeof MagazineLightingIdeasRoute
  '/magazine/materials-guide': typeof MagazineMaterialsGuideRoute
  '/magazine/room-ideas': typeof MagazineRoomIdeasRoute
  '/magazine/vastu-tips': typeof MagazineVastuTipsRoute
  '/magazine/wall-design-ideas': typeof MagazineWallDesignIdeasRoute
  '/cities/': typeof CitiesIndexRoute
  '/design-ideas/': typeof DesignIdeasIndexRoute
  '/magazine/': typeof MagazineIndexRoute
  '/magazine/blog/$slug': typeof MagazineBlogSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/cities'
    | '/dashboard'
    | '/design-ideas'
    | '/hire-a-designer'
    | '/login'
    | '/luxury-interiors'
    | '/magazine'
    | '/price-calculator'
    | '/projects'
    | '/store-locator'
    | '/cities/$city'
    | '/design-ideas/$slug'
    | '/design-ideas/balcony-designs'
    | '/design-ideas/bathroom-designs'
    | '/design-ideas/crockery-units'
    | '/design-ideas/dining-room-designs'
    | '/design-ideas/door-designs'
    | '/design-ideas/false-ceiling-designs'
    | '/design-ideas/flooring-designs'
    | '/design-ideas/foyer-designs'
    | '/design-ideas/guest-bedroom-designs'
    | '/design-ideas/home-bar-designs'
    | '/design-ideas/home-office-designs'
    | '/design-ideas/home-wallpaper-designs'
    | '/design-ideas/homes-by-nextgen'
    | '/design-ideas/kids-bedroom-designs'
    | '/design-ideas/kitchen-designs'
    | '/design-ideas/kitchen-sinks'
    | '/design-ideas/living-room-designs'
    | '/design-ideas/master-bedroom-designs'
    | '/design-ideas/pooja-room-designs'
    | '/design-ideas/space-saving-designs'
    | '/design-ideas/staircase-designs'
    | '/design-ideas/study-room-designs'
    | '/design-ideas/tile-designs'
    | '/design-ideas/tv-unit-designs'
    | '/design-ideas/wall-decor-designs'
    | '/design-ideas/wall-paint-designs'
    | '/design-ideas/wardrobe-designs'
    | '/design-ideas/window-designs'
    | '/magazine/$slug'
    | '/magazine/ceiling-design'
    | '/magazine/commercial-interiors'
    | '/magazine/decor-and-inspiration'
    | '/magazine/expert-advice'
    | '/magazine/furniture-ideas'
    | '/magazine/home-decor'
    | '/magazine/home-organisation'
    | '/magazine/home-renovation-ideas'
    | '/magazine/interior-advice'
    | '/magazine/lighting-ideas'
    | '/magazine/materials-guide'
    | '/magazine/room-ideas'
    | '/magazine/vastu-tips'
    | '/magazine/wall-design-ideas'
    | '/cities/'
    | '/design-ideas/'
    | '/magazine/'
    | '/magazine/blog/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/dashboard'
    | '/hire-a-designer'
    | '/login'
    | '/luxury-interiors'
    | '/price-calculator'
    | '/projects'
    | '/store-locator'
    | '/cities/$city'
    | '/design-ideas/$slug'
    | '/design-ideas/balcony-designs'
    | '/design-ideas/bathroom-designs'
    | '/design-ideas/crockery-units'
    | '/design-ideas/dining-room-designs'
    | '/design-ideas/door-designs'
    | '/design-ideas/false-ceiling-designs'
    | '/design-ideas/flooring-designs'
    | '/design-ideas/foyer-designs'
    | '/design-ideas/guest-bedroom-designs'
    | '/design-ideas/home-bar-designs'
    | '/design-ideas/home-office-designs'
    | '/design-ideas/home-wallpaper-designs'
    | '/design-ideas/homes-by-nextgen'
    | '/design-ideas/kids-bedroom-designs'
    | '/design-ideas/kitchen-designs'
    | '/design-ideas/kitchen-sinks'
    | '/design-ideas/living-room-designs'
    | '/design-ideas/master-bedroom-designs'
    | '/design-ideas/pooja-room-designs'
    | '/design-ideas/space-saving-designs'
    | '/design-ideas/staircase-designs'
    | '/design-ideas/study-room-designs'
    | '/design-ideas/tile-designs'
    | '/design-ideas/tv-unit-designs'
    | '/design-ideas/wall-decor-designs'
    | '/design-ideas/wall-paint-designs'
    | '/design-ideas/wardrobe-designs'
    | '/design-ideas/window-designs'
    | '/magazine/$slug'
    | '/magazine/ceiling-design'
    | '/magazine/commercial-interiors'
    | '/magazine/decor-and-inspiration'
    | '/magazine/expert-advice'
    | '/magazine/furniture-ideas'
    | '/magazine/home-decor'
    | '/magazine/home-organisation'
    | '/magazine/home-renovation-ideas'
    | '/magazine/interior-advice'
    | '/magazine/lighting-ideas'
    | '/magazine/materials-guide'
    | '/magazine/room-ideas'
    | '/magazine/vastu-tips'
    | '/magazine/wall-design-ideas'
    | '/cities'
    | '/design-ideas'
    | '/magazine'
    | '/magazine/blog/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/cities'
    | '/dashboard'
    | '/design-ideas'
    | '/hire-a-designer'
    | '/login'
    | '/luxury-interiors'
    | '/magazine'
    | '/price-calculator'
    | '/projects'
    | '/store-locator'
    | '/cities/$city'
    | '/design-ideas/$slug'
    | '/design-ideas/balcony-designs'
    | '/design-ideas/bathroom-designs'
    | '/design-ideas/crockery-units'
    | '/design-ideas/dining-room-designs'
    | '/design-ideas/door-designs'
    | '/design-ideas/false-ceiling-designs'
    | '/design-ideas/flooring-designs'
    | '/design-ideas/foyer-designs'
    | '/design-ideas/guest-bedroom-designs'
    | '/design-ideas/home-bar-designs'
    | '/design-ideas/home-office-designs'
    | '/design-ideas/home-wallpaper-designs'
    | '/design-ideas/homes-by-nextgen'
    | '/design-ideas/kids-bedroom-designs'
    | '/design-ideas/kitchen-designs'
    | '/design-ideas/kitchen-sinks'
    | '/design-ideas/living-room-designs'
    | '/design-ideas/master-bedroom-designs'
    | '/design-ideas/pooja-room-designs'
    | '/design-ideas/space-saving-designs'
    | '/design-ideas/staircase-designs'
    | '/design-ideas/study-room-designs'
    | '/design-ideas/tile-designs'
    | '/design-ideas/tv-unit-designs'
    | '/design-ideas/wall-decor-designs'
    | '/design-ideas/wall-paint-designs'
    | '/design-ideas/wardrobe-designs'
    | '/design-ideas/window-designs'
    | '/magazine/$slug'
    | '/magazine/ceiling-design'
    | '/magazine/commercial-interiors'
    | '/magazine/decor-and-inspiration'
    | '/magazine/expert-advice'
    | '/magazine/furniture-ideas'
    | '/magazine/home-decor'
    | '/magazine/home-organisation'
    | '/magazine/home-renovation-ideas'
    | '/magazine/interior-advice'
    | '/magazine/lighting-ideas'
    | '/magazine/materials-guide'
    | '/magazine/room-ideas'
    | '/magazine/vastu-tips'
    | '/magazine/wall-design-ideas'
    | '/cities/'
    | '/design-ideas/'
    | '/magazine/'
    | '/magazine/blog/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  CitiesRoute: typeof CitiesRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DesignIdeasRoute: typeof DesignIdeasRouteWithChildren
  HireADesignerRoute: typeof HireADesignerRoute
  LoginRoute: typeof LoginRoute
  LuxuryInteriorsRoute: typeof LuxuryInteriorsRoute
  MagazineRoute: typeof MagazineRouteWithChildren
  PriceCalculatorRoute: typeof PriceCalculatorRoute
  ProjectsRoute: typeof ProjectsRoute
  StoreLocatorRoute: typeof StoreLocatorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/store-locator': {
      id: '/store-locator'
      path: '/store-locator'
      fullPath: '/store-locator'
      preLoaderRoute: typeof StoreLocatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/price-calculator': {
      id: '/price-calculator'
      path: '/price-calculator'
      fullPath: '/price-calculator'
      preLoaderRoute: typeof PriceCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magazine': {
      id: '/magazine'
      path: '/magazine'
      fullPath: '/magazine'
      preLoaderRoute: typeof MagazineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/luxury-interiors': {
      id: '/luxury-interiors'
      path: '/luxury-interiors'
      fullPath: '/luxury-interiors'
      preLoaderRoute: typeof LuxuryInteriorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire-a-designer': {
      id: '/hire-a-designer'
      path: '/hire-a-designer'
      fullPath: '/hire-a-designer'
      preLoaderRoute: typeof HireADesignerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-ideas': {
      id: '/design-ideas'
      path: '/design-ideas'
      fullPath: '/design-ideas'
      preLoaderRoute: typeof DesignIdeasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities': {
      id: '/cities'
      path: '/cities'
      fullPath: '/cities'
      preLoaderRoute: typeof CitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magazine/': {
      id: '/magazine/'
      path: '/'
      fullPath: '/magazine/'
      preLoaderRoute: typeof MagazineIndexRouteImport
      parentRoute: typeof MagazineRoute
    }
    '/design-ideas/': {
      id: '/design-ideas/'
      path: '/'
      fullPath: '/design-ideas/'
      preLoaderRoute: typeof DesignIdeasIndexRouteImport
      parentRoute: typeof DesignIdeasRoute
    }
    '/cities/': {
      id: '/cities/'
      path: '/'
      fullPath: '/cities/'
      preLoaderRoute: typeof CitiesIndexRouteImport
      parentRoute: typeof CitiesRoute
    }
    '/magazine/wall-design-ideas': {
      id: '/magazine/wall-design-ideas'
      path: '/wall-design-ideas'
      fullPath: '/magazine/wall-design-ideas'
      preLoaderRoute: typeof MagazineWallDesignIdeasRouteImport
      parentRoute: typeof MagazineRoute
    }
    '/magazine/vastu-tips': {
      id: '/magazine/vastu-tips'
      path: '/vastu-tips'
      fullPath: '/magazine/vastu-tips'
      preLoaderRoute: typeof MagazineVastuTipsRouteImport
      parentRoute: typeof MagazineRoute
    }
    '/magazine/room-ideas': {
      id: '/magazine/room-ideas'
      path: '/room-ideas'
      fullPath: '/magazine/room-ideas'
      preLoaderRoute: typeof MagazineRoomIdeasRouteImport
      parentRoute: typeof MagazineRoute
    }
    '/magazine/materials-guide': {
      id: '/magazine/materials-guide'
      path: '/materials-guide'
      fullPath: '/magazine/materials-guide'
      preLoaderRoute: typeof MagazineMaterialsGuideRouteImport
      parentRoute: typeof MagazineRoute
    }
    '/magazine/lighting-ideas': {
      id: '/magazine/lighting-ideas'
      path: '/lighting-ideas'
      fullPath: '/magazine/lighting-ideas'
      preLoaderRoute: typeof MagazineLightingIdeasRouteImport
      parentRoute: typeof MagazineRoute
    }
    '/magazine/interior-advice': {
      id: '/magazine/interior-advice'
      path: '/interior-advice'
      fullPath: '/magazine/interior-advice'
      preLoaderRoute: typeof MagazineInteriorAdviceRouteImport
      parentRoute: typeof MagazineRoute
    }
    '/magazine/home-renovation-ideas': {
      id: '/magazine/home-renovation-ideas'
      path: '/home-renovation-ideas'
      fullPath: '/magazine/home-renovation-ideas'
      preLoaderRoute: typeof MagazineHomeRenovationIdeasRouteImport
      parentRoute: typeof MagazineRoute
    }
    '/magazine/home-organisation': {
      id: '/magazine/home-organisation'
      path: '/home-organisation'
      fullPath: '/magazine/home-organisation'
      preLoaderRoute: typeof MagazineHomeOrganisationRouteImport
      parentRoute: typeof MagazineRoute
    }
    '/magazine/home-decor': {
      id: '/magazine/home-decor'
      path: '/home-decor'
      fullPath: '/magazine/home-decor'
      preLoaderRoute: typeof MagazineHomeDecorRouteImport
      parentRoute: typeof MagazineRoute
    }
    '/magazine/furniture-ideas': {
      id: '/magazine/furniture-ideas'
      path: '/furniture-ideas'
      fullPath: '/magazine/furniture-ideas'
      preLoaderRoute: typeof MagazineFurnitureIdeasRouteImport
      parentRoute: typeof MagazineRoute
    }
    '/magazine/expert-advice': {
      id: '/magazine/expert-advice'
      path: '/expert-advice'
      fullPath: '/magazine/expert-advice'
      preLoaderRoute: typeof MagazineExpertAdviceRouteImport
      parentRoute: typeof MagazineRoute
    }
    '/magazine/decor-and-inspiration': {
      id: '/magazine/decor-and-inspiration'
      path: '/decor-and-inspiration'
      fullPath: '/magazine/decor-and-inspiration'
      preLoaderRoute: typeof MagazineDecorAndInspirationRouteImport
      parentRoute: typeof MagazineRoute
    }
    '/magazine/commercial-interiors': {
      id: '/magazine/commercial-interiors'
      path: '/commercial-interiors'
      fullPath: '/magazine/commercial-interiors'
      preLoaderRoute: typeof MagazineCommercialInteriorsRouteImport
      parentRoute: typeof MagazineRoute
    }
    '/magazine/ceiling-design': {
      id: '/magazine/ceiling-design'
      path: '/ceiling-design'
      fullPath: '/magazine/ceiling-design'
      preLoaderRoute: typeof MagazineCeilingDesignRouteImport
      parentRoute: typeof MagazineRoute
    }
    '/magazine/$slug': {
      id: '/magazine/$slug'
      path: '/$slug'
      fullPath: '/magazine/$slug'
      preLoaderRoute: typeof MagazineSlugRouteImport
      parentRoute: typeof MagazineRoute
    }
    '/design-ideas/window-designs': {
      id: '/design-ideas/window-designs'
      path: '/window-designs'
      fullPath: '/design-ideas/window-designs'
      preLoaderRoute: typeof DesignIdeasWindowDesignsRouteImport
      parentRoute: typeof DesignIdeasRoute
    }
    '/design-ideas/wardrobe-designs': {
      id: '/design-ideas/wardrobe-designs'
      path: '/wardrobe-designs'
      fullPath: '/design-ideas/wardrobe-designs'
      preLoaderRoute: typeof DesignIdeasWardrobeDesignsRouteImport
      parentRoute: typeof DesignIdeasRoute
    }
    '/design-ideas/wall-paint-designs': {
      id: '/design-ideas/wall-paint-designs'
      path: '/wall-paint-designs'
      fullPath: '/design-ideas/wall-paint-designs'
      preLoaderRoute: typeof DesignIdeasWallPaintDesignsRouteImport
      parentRoute: typeof DesignIdeasRoute
    }
    '/design-ideas/wall-decor-designs': {
      id: '/design-ideas/wall-decor-designs'
      path: '/wall-decor-designs'
      fullPath: '/design-ideas/wall-decor-designs'
      preLoaderRoute: typeof DesignIdeasWallDecorDesignsRouteImport
      parentRoute: typeof DesignIdeasRoute
    }
    '/design-ideas/tv-unit-designs': {
      id: '/design-ideas/tv-unit-designs'
      path: '/tv-unit-designs'
      fullPath: '/design-ideas/tv-unit-designs'
      preLoaderRoute: typeof DesignIdeasTvUnitDesignsRouteImport
      parentRoute: typeof DesignIdeasRoute
    }
    '/design-ideas/tile-designs': {
      id: '/design-ideas/tile-designs'
      path: '/tile-designs'
      fullPath: '/design-ideas/tile-designs'
      preLoaderRoute: typeof DesignIdeasTileDesignsRouteImport
      parentRoute: typeof DesignIdeasRoute
    }
    '/design-ideas/study-room-designs': {
      id: '/design-ideas/study-room-designs'
      path: '/study-room-designs'
      fullPath: '/design-ideas/study-room-designs'
      preLoaderRoute: typeof DesignIdeasStudyRoomDesignsRouteImport
      parentRoute: typeof DesignIdeasRoute
    }
    '/design-ideas/staircase-designs': {
      id: '/design-ideas/staircase-designs'
      path: '/staircase-designs'
      fullPath: '/design-ideas/staircase-designs'
      preLoaderRoute: typeof DesignIdeasStaircaseDesignsRouteImport
      parentRoute: typeof DesignIdeasRoute
    }
    '/design-ideas/space-saving-designs': {
      id: '/design-ideas/space-saving-designs'
      path: '/space-saving-designs'
      fullPath: '/design-ideas/space-saving-designs'
      preLoaderRoute: typeof DesignIdeasSpaceSavingDesignsRouteImport
      parentRoute: typeof DesignIdeasRoute
    }
    '/design-ideas/pooja-room-designs': {
      id: '/design-ideas/pooja-room-designs'
      path: '/pooja-room-designs'
      fullPath: '/design-ideas/pooja-room-designs'
      preLoaderRoute: typeof DesignIdeasPoojaRoomDesignsRouteImport
      parentRoute: typeof DesignIdeasRoute
    }
    '/design-ideas/master-bedroom-designs': {
      id: '/design-ideas/master-bedroom-designs'
      path: '/master-bedroom-designs'
      fullPath: '/design-ideas/master-bedroom-designs'
      preLoaderRoute: typeof DesignIdeasMasterBedroomDesignsRouteImport
      parentRoute: typeof DesignIdeasRoute
    }
    '/design-ideas/living-room-designs': {
      id: '/design-ideas/living-room-designs'
      path: '/living-room-designs'
      fullPath: '/design-ideas/living-room-designs'
      preLoaderRoute: typeof DesignIdeasLivingRoomDesignsRouteImport
      parentRoute: typeof DesignIdeasRoute
    }
    '/design-ideas/kitchen-sinks': {
      id: '/design-ideas/kitchen-sinks'
      path: '/kitchen-sinks'
      fullPath: '/design-ideas/kitchen-sinks'
      preLoaderRoute: typeof DesignIdeasKitchenSinksRouteImport
      parentRoute: typeof DesignIdeasRoute
    }
    '/design-ideas/kitchen-designs': {
      id: '/design-ideas/kitchen-designs'
      path: '/kitchen-designs'
      fullPath: '/design-ideas/kitchen-designs'
      preLoaderRoute: typeof DesignIdeasKitchenDesignsRouteImport
      parentRoute: typeof DesignIdeasRoute
    }
    '/design-ideas/kids-bedroom-designs': {
      id: '/design-ideas/kids-bedroom-designs'
      path: '/kids-bedroom-designs'
      fullPath: '/design-ideas/kids-bedroom-designs'
      preLoaderRoute: typeof DesignIdeasKidsBedroomDesignsRouteImport
      parentRoute: typeof DesignIdeasRoute
    }
    '/design-ideas/homes-by-nextgen': {
      id: '/design-ideas/homes-by-nextgen'
      path: '/homes-by-nextgen'
      fullPath: '/design-ideas/homes-by-nextgen'
      preLoaderRoute: typeof DesignIdeasHomesByNextgenRouteImport
      parentRoute: typeof DesignIdeasRoute
    }
    '/design-ideas/home-wallpaper-designs': {
      id: '/design-ideas/home-wallpaper-designs'
      path: '/home-wallpaper-designs'
      fullPath: '/design-ideas/home-wallpaper-designs'
      preLoaderRoute: typeof DesignIdeasHomeWallpaperDesignsRouteImport
      parentRoute: typeof DesignIdeasRoute
    }
    '/design-ideas/home-office-designs': {
      id: '/design-ideas/home-office-designs'
      path: '/home-office-designs'
      fullPath: '/design-ideas/home-office-designs'
      preLoaderRoute: typeof DesignIdeasHomeOfficeDesignsRouteImport
      parentRoute: typeof DesignIdeasRoute
    }
    '/design-ideas/home-bar-designs': {
      id: '/design-ideas/home-bar-designs'
      path: '/home-bar-designs'
      fullPath: '/design-ideas/home-bar-designs'
      preLoaderRoute: typeof DesignIdeasHomeBarDesignsRouteImport
      parentRoute: typeof DesignIdeasRoute
    }
    '/design-ideas/guest-bedroom-designs': {
      id: '/design-ideas/guest-bedroom-designs'
      path: '/guest-bedroom-designs'
      fullPath: '/design-ideas/guest-bedroom-designs'
      preLoaderRoute: typeof DesignIdeasGuestBedroomDesignsRouteImport
      parentRoute: typeof DesignIdeasRoute
    }
    '/design-ideas/foyer-designs': {
      id: '/design-ideas/foyer-designs'
      path: '/foyer-designs'
      fullPath: '/design-ideas/foyer-designs'
      preLoaderRoute: typeof DesignIdeasFoyerDesignsRouteImport
      parentRoute: typeof DesignIdeasRoute
    }
    '/design-ideas/flooring-designs': {
      id: '/design-ideas/flooring-designs'
      path: '/flooring-designs'
      fullPath: '/design-ideas/flooring-designs'
      preLoaderRoute: typeof DesignIdeasFlooringDesignsRouteImport
      parentRoute: typeof DesignIdeasRoute
    }
    '/design-ideas/false-ceiling-designs': {
      id: '/design-ideas/false-ceiling-designs'
      path: '/false-ceiling-designs'
      fullPath: '/design-ideas/false-ceiling-designs'
      preLoaderRoute: typeof DesignIdeasFalseCeilingDesignsRouteImport
      parentRoute: typeof DesignIdeasRoute
    }
    '/design-ideas/door-designs': {
      id: '/design-ideas/door-designs'
      path: '/door-designs'
      fullPath: '/design-ideas/door-designs'
      preLoaderRoute: typeof DesignIdeasDoorDesignsRouteImport
      parentRoute: typeof DesignIdeasRoute
    }
    '/design-ideas/dining-room-designs': {
      id: '/design-ideas/dining-room-designs'
      path: '/dining-room-designs'
      fullPath: '/design-ideas/dining-room-designs'
      preLoaderRoute: typeof DesignIdeasDiningRoomDesignsRouteImport
      parentRoute: typeof DesignIdeasRoute
    }
    '/design-ideas/crockery-units': {
      id: '/design-ideas/crockery-units'
      path: '/crockery-units'
      fullPath: '/design-ideas/crockery-units'
      preLoaderRoute: typeof DesignIdeasCrockeryUnitsRouteImport
      parentRoute: typeof DesignIdeasRoute
    }
    '/design-ideas/bathroom-designs': {
      id: '/design-ideas/bathroom-designs'
      path: '/bathroom-designs'
      fullPath: '/design-ideas/bathroom-designs'
      preLoaderRoute: typeof DesignIdeasBathroomDesignsRouteImport
      parentRoute: typeof DesignIdeasRoute
    }
    '/design-ideas/balcony-designs': {
      id: '/design-ideas/balcony-designs'
      path: '/balcony-designs'
      fullPath: '/design-ideas/balcony-designs'
      preLoaderRoute: typeof DesignIdeasBalconyDesignsRouteImport
      parentRoute: typeof DesignIdeasRoute
    }
    '/design-ideas/$slug': {
      id: '/design-ideas/$slug'
      path: '/$slug'
      fullPath: '/design-ideas/$slug'
      preLoaderRoute: typeof DesignIdeasSlugRouteImport
      parentRoute: typeof DesignIdeasRoute
    }
    '/cities/$city': {
      id: '/cities/$city'
      path: '/$city'
      fullPath: '/cities/$city'
      preLoaderRoute: typeof CitiesCityRouteImport
      parentRoute: typeof CitiesRoute
    }
    '/magazine/blog/$slug': {
      id: '/magazine/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/magazine/blog/$slug'
      preLoaderRoute: typeof MagazineBlogSlugRouteImport
      parentRoute: typeof MagazineRoute
    }
  }
}

interface CitiesRouteChildren {
  CitiesCityRoute: typeof CitiesCityRoute
  CitiesIndexRoute: typeof CitiesIndexRoute
}

const CitiesRouteChildren: CitiesRouteChildren = {
  CitiesCityRoute: CitiesCityRoute,
  CitiesIndexRoute: CitiesIndexRoute,
}

const CitiesRouteWithChildren =
  CitiesRoute._addFileChildren(CitiesRouteChildren)

interface DesignIdeasRouteChildren {
  DesignIdeasSlugRoute: typeof DesignIdeasSlugRoute
  DesignIdeasBalconyDesignsRoute: typeof DesignIdeasBalconyDesignsRoute
  DesignIdeasBathroomDesignsRoute: typeof DesignIdeasBathroomDesignsRoute
  DesignIdeasCrockeryUnitsRoute: typeof DesignIdeasCrockeryUnitsRoute
  DesignIdeasDiningRoomDesignsRoute: typeof DesignIdeasDiningRoomDesignsRoute
  DesignIdeasDoorDesignsRoute: typeof DesignIdeasDoorDesignsRoute
  DesignIdeasFalseCeilingDesignsRoute: typeof DesignIdeasFalseCeilingDesignsRoute
  DesignIdeasFlooringDesignsRoute: typeof DesignIdeasFlooringDesignsRoute
  DesignIdeasFoyerDesignsRoute: typeof DesignIdeasFoyerDesignsRoute
  DesignIdeasGuestBedroomDesignsRoute: typeof DesignIdeasGuestBedroomDesignsRoute
  DesignIdeasHomeBarDesignsRoute: typeof DesignIdeasHomeBarDesignsRoute
  DesignIdeasHomeOfficeDesignsRoute: typeof DesignIdeasHomeOfficeDesignsRoute
  DesignIdeasHomeWallpaperDesignsRoute: typeof DesignIdeasHomeWallpaperDesignsRoute
  DesignIdeasHomesByNextgenRoute: typeof DesignIdeasHomesByNextgenRoute
  DesignIdeasKidsBedroomDesignsRoute: typeof DesignIdeasKidsBedroomDesignsRoute
  DesignIdeasKitchenDesignsRoute: typeof DesignIdeasKitchenDesignsRoute
  DesignIdeasKitchenSinksRoute: typeof DesignIdeasKitchenSinksRoute
  DesignIdeasLivingRoomDesignsRoute: typeof DesignIdeasLivingRoomDesignsRoute
  DesignIdeasMasterBedroomDesignsRoute: typeof DesignIdeasMasterBedroomDesignsRoute
  DesignIdeasPoojaRoomDesignsRoute: typeof DesignIdeasPoojaRoomDesignsRoute
  DesignIdeasSpaceSavingDesignsRoute: typeof DesignIdeasSpaceSavingDesignsRoute
  DesignIdeasStaircaseDesignsRoute: typeof DesignIdeasStaircaseDesignsRoute
  DesignIdeasStudyRoomDesignsRoute: typeof DesignIdeasStudyRoomDesignsRoute
  DesignIdeasTileDesignsRoute: typeof DesignIdeasTileDesignsRoute
  DesignIdeasTvUnitDesignsRoute: typeof DesignIdeasTvUnitDesignsRoute
  DesignIdeasWallDecorDesignsRoute: typeof DesignIdeasWallDecorDesignsRoute
  DesignIdeasWallPaintDesignsRoute: typeof DesignIdeasWallPaintDesignsRoute
  DesignIdeasWardrobeDesignsRoute: typeof DesignIdeasWardrobeDesignsRoute
  DesignIdeasWindowDesignsRoute: typeof DesignIdeasWindowDesignsRoute
  DesignIdeasIndexRoute: typeof DesignIdeasIndexRoute
}

const DesignIdeasRouteChildren: DesignIdeasRouteChildren = {
  DesignIdeasSlugRoute: DesignIdeasSlugRoute,
  DesignIdeasBalconyDesignsRoute: DesignIdeasBalconyDesignsRoute,
  DesignIdeasBathroomDesignsRoute: DesignIdeasBathroomDesignsRoute,
  DesignIdeasCrockeryUnitsRoute: DesignIdeasCrockeryUnitsRoute,
  DesignIdeasDiningRoomDesignsRoute: DesignIdeasDiningRoomDesignsRoute,
  DesignIdeasDoorDesignsRoute: DesignIdeasDoorDesignsRoute,
  DesignIdeasFalseCeilingDesignsRoute: DesignIdeasFalseCeilingDesignsRoute,
  DesignIdeasFlooringDesignsRoute: DesignIdeasFlooringDesignsRoute,
  DesignIdeasFoyerDesignsRoute: DesignIdeasFoyerDesignsRoute,
  DesignIdeasGuestBedroomDesignsRoute: DesignIdeasGuestBedroomDesignsRoute,
  DesignIdeasHomeBarDesignsRoute: DesignIdeasHomeBarDesignsRoute,
  DesignIdeasHomeOfficeDesignsRoute: DesignIdeasHomeOfficeDesignsRoute,
  DesignIdeasHomeWallpaperDesignsRoute: DesignIdeasHomeWallpaperDesignsRoute,
  DesignIdeasHomesByNextgenRoute: DesignIdeasHomesByNextgenRoute,
  DesignIdeasKidsBedroomDesignsRoute: DesignIdeasKidsBedroomDesignsRoute,
  DesignIdeasKitchenDesignsRoute: DesignIdeasKitchenDesignsRoute,
  DesignIdeasKitchenSinksRoute: DesignIdeasKitchenSinksRoute,
  DesignIdeasLivingRoomDesignsRoute: DesignIdeasLivingRoomDesignsRoute,
  DesignIdeasMasterBedroomDesignsRoute: DesignIdeasMasterBedroomDesignsRoute,
  DesignIdeasPoojaRoomDesignsRoute: DesignIdeasPoojaRoomDesignsRoute,
  DesignIdeasSpaceSavingDesignsRoute: DesignIdeasSpaceSavingDesignsRoute,
  DesignIdeasStaircaseDesignsRoute: DesignIdeasStaircaseDesignsRoute,
  DesignIdeasStudyRoomDesignsRoute: DesignIdeasStudyRoomDesignsRoute,
  DesignIdeasTileDesignsRoute: DesignIdeasTileDesignsRoute,
  DesignIdeasTvUnitDesignsRoute: DesignIdeasTvUnitDesignsRoute,
  DesignIdeasWallDecorDesignsRoute: DesignIdeasWallDecorDesignsRoute,
  DesignIdeasWallPaintDesignsRoute: DesignIdeasWallPaintDesignsRoute,
  DesignIdeasWardrobeDesignsRoute: DesignIdeasWardrobeDesignsRoute,
  DesignIdeasWindowDesignsRoute: DesignIdeasWindowDesignsRoute,
  DesignIdeasIndexRoute: DesignIdeasIndexRoute,
}

const DesignIdeasRouteWithChildren = DesignIdeasRoute._addFileChildren(
  DesignIdeasRouteChildren,
)

interface MagazineRouteChildren {
  MagazineSlugRoute: typeof MagazineSlugRoute
  MagazineCeilingDesignRoute: typeof MagazineCeilingDesignRoute
  MagazineCommercialInteriorsRoute: typeof MagazineCommercialInteriorsRoute
  MagazineDecorAndInspirationRoute: typeof MagazineDecorAndInspirationRoute
  MagazineExpertAdviceRoute: typeof MagazineExpertAdviceRoute
  MagazineFurnitureIdeasRoute: typeof MagazineFurnitureIdeasRoute
  MagazineHomeDecorRoute: typeof MagazineHomeDecorRoute
  MagazineHomeOrganisationRoute: typeof MagazineHomeOrganisationRoute
  MagazineHomeRenovationIdeasRoute: typeof MagazineHomeRenovationIdeasRoute
  MagazineInteriorAdviceRoute: typeof MagazineInteriorAdviceRoute
  MagazineLightingIdeasRoute: typeof MagazineLightingIdeasRoute
  MagazineMaterialsGuideRoute: typeof MagazineMaterialsGuideRoute
  MagazineRoomIdeasRoute: typeof MagazineRoomIdeasRoute
  MagazineVastuTipsRoute: typeof MagazineVastuTipsRoute
  MagazineWallDesignIdeasRoute: typeof MagazineWallDesignIdeasRoute
  MagazineIndexRoute: typeof MagazineIndexRoute
  MagazineBlogSlugRoute: typeof MagazineBlogSlugRoute
}

const MagazineRouteChildren: MagazineRouteChildren = {
  MagazineSlugRoute: MagazineSlugRoute,
  MagazineCeilingDesignRoute: MagazineCeilingDesignRoute,
  MagazineCommercialInteriorsRoute: MagazineCommercialInteriorsRoute,
  MagazineDecorAndInspirationRoute: MagazineDecorAndInspirationRoute,
  MagazineExpertAdviceRoute: MagazineExpertAdviceRoute,
  MagazineFurnitureIdeasRoute: MagazineFurnitureIdeasRoute,
  MagazineHomeDecorRoute: MagazineHomeDecorRoute,
  MagazineHomeOrganisationRoute: MagazineHomeOrganisationRoute,
  MagazineHomeRenovationIdeasRoute: MagazineHomeRenovationIdeasRoute,
  MagazineInteriorAdviceRoute: MagazineInteriorAdviceRoute,
  MagazineLightingIdeasRoute: MagazineLightingIdeasRoute,
  MagazineMaterialsGuideRoute: MagazineMaterialsGuideRoute,
  MagazineRoomIdeasRoute: MagazineRoomIdeasRoute,
  MagazineVastuTipsRoute: MagazineVastuTipsRoute,
  MagazineWallDesignIdeasRoute: MagazineWallDesignIdeasRoute,
  MagazineIndexRoute: MagazineIndexRoute,
  MagazineBlogSlugRoute: MagazineBlogSlugRoute,
}

const MagazineRouteWithChildren = MagazineRoute._addFileChildren(
  MagazineRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  CitiesRoute: CitiesRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DesignIdeasRoute: DesignIdeasRouteWithChildren,
  HireADesignerRoute: HireADesignerRoute,
  LoginRoute: LoginRoute,
  LuxuryInteriorsRoute: LuxuryInteriorsRoute,
  MagazineRoute: MagazineRouteWithChildren,
  PriceCalculatorRoute: PriceCalculatorRoute,
  ProjectsRoute: ProjectsRoute,
  StoreLocatorRoute: StoreLocatorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
